name: Lighthouse Audit
on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  lhci:
    name: Run Lighthouse
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18.17.1

      - name: Install Dependencies
        run: npm install

      - name: Build Site
        run: npm run build

      - name: Install Lighthouse CLI
        run: npm install -g @lhci/cli@0.13.0

      - name: Run Lighthouse CLI
        run: lhci autorun
        env:
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}

      - name: Write Lighthouse Results
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const path = require('path');
            const reportPath = './.lighthouseci';
            let commentBody = '### Lighthouse Results\n';

            const files = fs.readdirSync(reportPath);
            files.forEach(file => {
              if (file.includes('links')) return; // Skip links.json
              if (path.extname(file) === '.json') {
                const report = JSON.parse(fs.readFileSync(path.join(reportPath, file)));
                const url = report.requestedUrl;
                if (url) {
                  const page = new URL(url).pathname.substring(1);
                  commentBody += `**Page:** ${page} `;
                }

                if (report.categories && typeof report.categories === 'object') {
                  Object.keys(report.categories).forEach((categoryKey) => {
                    const category = report.categories[categoryKey];
                    commentBody += `**${category.title[0]}:** ${Math.round(category.score * 100)}`;
                  });
                } else {
                  commentBody += 'No categories found in report.\n';
                }

                commentBody += '\n';
              }
            });

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: commentBody,
            })
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
