name: Run Lighthouse CI

on:
  # Trigger the workflow every time you push to the `main` branch
  # Using a different branch name? Replace `main` with your branch’s name
  push:
    branches:
      - main

  # Allows you to run this workflow manually from the Actions tab on GitHub.
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install, build, and upload your site output
        uses: withastro/action@v1
        with:
          node-version: 18.17.1
          package-manager: pnpm@8.12.0

      - name: Upload dist folder
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist

  static-dist-dir:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Display current working directory
        run: cwd
      - name: Download dist folder
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: ./dist
      - name: Display structure of dist files
        run: ls -R dist
      - name: Display current working directory
        run: cwd

      - name: Run Lighthouse against static site files
        uses: treosh/lighthouse-ci-action@v11
        with:
          budgetPath: .github/workflows/budget.json
          configPath: .github/workflows/lighthouserc.json
          uploadArtifacts: true
          artifactName: lighthouse-report
      - name: Display current working directory
        run: cwd
