name: Lighthouse Audit
on:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  lhci:
    name: Run Lighthouse
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18.17.1

      - name: Install Dependencies
        run: npm install

      - name: Build Site
        run: npm run build

      - name: Install Lighthouse CLI
        run: npm install -g @lhci/cli@0.13.0

      - name: Run Lighthouse CLI
        run: lhci autorun
        env:
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}

      - name: Write Lighthouse Results
        uses: actions/github-script@v7
        with:
          script: |
            const lighthouseScript = require('./path/to/script.js')
            console.log(lighthouseScript({github, context}))
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
