name: Lighthouse Audit
on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  lhci:
    name: Run Lighthouse
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18.17.1

      - name: Install Dependencies
        run: npm install

      - name: Build Site
        run: npm run build

      - name: Install Lighthouse CLI
        run: npm install -g @lhci/cli@0.13.0

      - name: Run Lighthouse CLI
        run: lhci autorun
        env:
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}

      - name: Add Lighthouse Results
        uses: actions/github-script@v5
        with:
          script: |
            const fs = require('fs');
            const path = require('path');
            const reportPath = './.lighthouseci'; // Adjust based on where your reports are saved
            const files = fs.readdirSync(reportPath);

            let commentBody = '### Lighthouse Results\n';
            files.forEach(file => {
              if (path.extname(file) === '.json') {
                const report = JSON.parse(fs.readFileSync(path.join(reportPath, file)));
                const url = report.requestedUrl;
                commentBody += `**URL:** ${url}\n`;
                report.categories.forEach(category => {
                  commentBody += `**${category.title}:** ${category.score * 100}\n`;
                });
                commentBody += '\n';
              }
            });

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: commentBody,
            })
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
